version: '2'
services:
  web:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: >
      sh -c "django-admin makemigrations --pythonpath /code --settings cabot.settings -v 3 &&
      django-admin migrate --pythonpath /code --settings cabot.settings -v 3 &&
      django-admin runserver --pythonpath /code 0.0.0.0:5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
      - worker
      - beat
      - events

  worker:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: celery worker -A cabot --loglevel=DEBUG --concurrency=16 -Ofair
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    depends_on:
      - postgres
      - rabbitmq
      - events

  beat:
    extends:
      file: docker-compose-base.yml
      service: base
    env_file:
      - conf/development.env
    command: celery beat -A cabot --loglevel=DEBUG
    environment:
      - SKIP_INIT=1
      - WAIT_FOR_MIGRATIONS=1
    depends_on:
      - postgres
      - rabbitmq
      - events

  events:
    extends:
      file: docker-compose-base.yml
      service: base
    command: celery -A cabot events -l info --camera django_celery_monitor.camera.Camera
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ../data:/var/lib/postgresql/data

volumes:
  datavolume:
